#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d94hepuq1p3s73bn6eb0-a.singapore-postgres.render.com:5432/moneymanager_xdem
spring.datasource.username=moneymanager_xdem_user
spring.datasource.password=hLWeKahO7SlGft46Axbn1fKuiJCo2tfz
spring.datasource.driver-class-name=org.postgresql.Driver